project_name: frabit-ctl
builds:
  - env: [CGO_ENABLED=0]
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
nfpms:
  - maintainer: Blylei <blylei.info@gmail.com>
    description: Create a golang project based golang-standards.
    homepage: https://github.com/frabit-io/frabit-ctl
    license: GPLv3
    formats:
      - deb
      - rpm
      - apk